void sysInit(void)
{
    RCC->APB2ENR |=
        RCC_APB2ENR_IOPAEN |
        RCC_APB2ENR_IOPBEN |
        RCC_APB2ENR_IOPCEN |
        RCC_APB2ENR_IOPDEN |
        RCC_APB2ENR_USART1EN |
				RCC_APB2ENR_AFIOEN;
	
	RCC->APB1ENR |= RCC_APB1ENR_USART2EN;
	
	return;
	//Button
	GPIOA->CRL &= ~GPIO_CRL_MODE0;
	GPIOA->CRL &= ~GPIO_CRL_CNF0;
	GPIOA->CRL |= GPIO_CRL_CNF0_1;
	
	//LEDS
	//Blue
 	GPIOC->CRH &= ~GPIO_CRH_MODE8;
 	GPIOC->CRH |= GPIO_CRH_MODE8_1;
 	GPIOC->CRH &= ~GPIO_CRH_CNF8;
 	//Green
 	GPIOC->CRH &= ~GPIO_CRH_MODE9;
  GPIOC->CRH |= GPIO_CRH_MODE9_1;
 	GPIOC->CRH &= ~GPIO_CRH_CNF9;
	
	//DHT11 POWER
	GPIOC->CRL &= ~GPIO_CRL_MODE7;
  GPIOC->CRL |= GPIO_CRL_MODE7_1;
 	GPIOC->CRL &= ~GPIO_CRL_CNF7;
	GPIOC->BSRR |= GPIO_BSRR_BS7;
	
	//DHT22 POWER
	GPIOC->CRL &= ~GPIO_CRL_MODE5;
  GPIOC->CRL |= GPIO_CRL_MODE5_1;
 	GPIOC->CRL &= ~GPIO_CRL_CNF5;
	GPIOC->BSRR |= GPIO_BSRR_BS5;
	
	//DHT22 GROUND
	GPIOB->CRL &= ~GPIO_CRL_MODE1;
  GPIOB->CRL |= GPIO_CRL_MODE1_1;
 	GPIOB->CRL &= ~GPIO_CRL_CNF1;
	GPIOB->BSRR |= GPIO_BSRR_BR1;	

	//DS18B20 GROUND 
	GPIOA->CRL &= ~GPIO_CRL_MODE4;
  GPIOA->CRL |= GPIO_CRL_MODE4_1;
 	GPIOA->CRL &= ~GPIO_CRL_CNF4;
	GPIOA->BSRR |= GPIO_BSRR_BR4;
		
	//DS18B20 POWER
	GPIOA->CRL &= ~GPIO_CRL_MODE1;
  GPIOA->CRL |= GPIO_CRL_MODE1_1;
 	GPIOA->CRL &= ~GPIO_CRL_CNF1;
	GPIOA->BSRR |= GPIO_BSRR_BS1;	

	
	//Timer6
	RCC->APB1ENR |= RCC_APB1ENR_TIM6EN;
	TIM6->PSC = 23999; // 24 000 000 Mhz / (23999 + 1) = 1000, 1 / 1000 = 1 mSec
	TIM6->ARR = 100; //100 mSec (counter reload)
	TIM6->CR1 |= TIM_CR1_CEN; //enable timer
	TIM6->DIER |= TIM_DIER_UIE; //enable interrupt
	
	__enable_irq();
	
	
	NVIC_EnableIRQ(TIM6_DAC_IRQn);
	NVIC_SetPriority(TIM6_DAC_IRQn, 2); 

}
