#ifndef MAIN_H_
#define MAIN_H_
/*
#define BUTTON (GPIOA->IDR & GPIO_IDR_IDR0)

#define LED_BLUE_ON  (GPIOC->BSRR |= GPIO_BSRR_BS8)
#define LED_BLUE_OFF (GPIOC->BSRR |= GPIO_BSRR_BR8)
#define LED_GREEN_ON  (GPIOC->BSRR |= GPIO_BSRR_BS9)
#define LED_GREEN_OFF (GPIOC->BSRR |= GPIO_BSRR_BR9)
*/
/*
#define DHT11_SET_OUT ( (GPIOC->CRL &= ~GPIO_CRL_MODE6) + (GPIOC->CRL |= GPIO_CRL_MODE6_1) + (GPIOC->CRL |= GPIO_CRL_CNF6_0)) // Open drain
#define DHT11_SET_IN  ( (GPIOC->CRL &= ~GPIO_CRL_MODE6) + (GPIOC->CRL &= ~GPIO_CRL_CNF6) + (GPIOC->CRL |= GPIO_CRL_CNF6_0))
#define DHT11_LOW	 		(GPIOC->BSRR |= GPIO_BSRR_BR6)
#define DHT11_HI 		 	(GPIOC->BSRR |= GPIO_BSRR_BS6)
#define DHT11_IN			(GPIOC->IDR & GPIO_IDR_IDR6)
*/

#define DHT11_SET_OUT ( (GPIOA->CRL &= ~GPIO_CRL_MODE6) + (GPIOA->CRL |= GPIO_CRL_MODE6_1) + (GPIOA->CRL |= GPIO_CRL_CNF6_0)) // Open drain
#define DHT11_SET_IN  ( (GPIOA->CRL &= ~GPIO_CRL_MODE6) + (GPIOA->CRL &= ~GPIO_CRL_CNF6) + (GPIOA->CRL |= GPIO_CRL_CNF6_0))
#define DHT11_LOW	 		(GPIOA->BSRR |= GPIO_BSRR_BR6)
#define DHT11_HI 		 	(GPIOA->BSRR |= GPIO_BSRR_BS6)
#define DHT11_IN			(GPIOA->IDR & GPIO_IDR_IDR6)


#define DHT22_SET_OUT ( (GPIOB->CRL &= ~GPIO_CRL_MODE0) + (GPIOB->CRL |= GPIO_CRL_MODE0_1) + (GPIOB->CRL |= GPIO_CRL_CNF0_0)) // Open drain
#define DHT22_SET_IN  ( (GPIOB->CRL &= ~GPIO_CRL_MODE0) + (GPIOB->CRL &= ~GPIO_CRL_CNF0) + (GPIOB->CRL |= GPIO_CRL_CNF0_0))
#define DHT22_LOW	 		(GPIOB->BSRR |= GPIO_BSRR_BR0)
#define DHT22_HI 		 	(GPIOB->BSRR |= GPIO_BSRR_BS0)
#define DHT22_IN			(GPIOB->IDR & GPIO_IDR_IDR0)

#endif
