#ifndef _PINMAP_H_
#define _PINMAP_H_

#include "macros.h"


// Old
#define CS_SOFT  B, 1, HIGH, MODE_OUTPUT_PUSH_PULL, SPEED_2MHZ		
	
#define LED1  B, 0, HIGH, MODE_OUTPUT_PUSH_PULL, SPEED_2MHZ	
#define LED2  B, 1, HIGH, MODE_OUTPUT_PUSH_PULL, SPEED_2MHZ	

#define PIN_BUTTON A, 0, HIGH, MODE_INPUT_FLOATING, SPEED_2MHZ
#define BOARD_LED  A, 5, HIGH, MODE_OUTPUT_PUSH_PULL, SPEED_2MHZ	
#define MAPPLE_LED  C, 13, HIGH, MODE_OUTPUT_PUSH_PULL, SPEED_2MHZ

#define USART1_TX A, 9,  HIGH, MODE_AF_PUSH_PULL, SPEED_50MHZ	
#define USART1_RX A, 10, HIGH, MODE_INPUT_FLOATING, SPEED_50MHZ
	
////////////////////////////////////////////////////////////////////

#define PMS_Rst  		D, 0, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ	
#define GP_LED  		D, 1, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ	
#define USR_BTN  		A, 0, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ	
#define ZE_DAC  		A, 1, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ	
#define PMS_Rx  		A, 2, 	HIGH, MODE_AF_PUSH_PULL, 			SPEED_50MHZ	
#define PMS_Tx  		A, 3, 	HIGH, MODE_INPUT_FLOATING, 		SPEED_50MHZ	
#define BQ_nEN  		A, 4, 	HIGH, MODE_INPUT_PULL_DOWN, 	SPEED_50MHZ	
#define BQ_nCHG  		A, 5, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ	
#define BQ_ISET2  	A, 6, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ	
#define BAT_ADC  		A, 7, 	HIGH, MODE_INPUT_ANALOG, 			SPEED_50MHZ	
#define DISC_USB  	A, 8, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ	
#define Radio_RxD  	A, 9, 	HIGH, MODE_AF_PUSH_PULL, 			SPEED_50MHZ	
#define Radio_TxD  	A, 10, 	HIGH, MODE_INPUT_FLOATING, 		SPEED_50MHZ	
#define DS18b20_Q  	A, 15, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ

#define GP_OUT  		B, 0, 	HIGH, MODE_OUTPUT_PUSH_PULL,	SPEED_50MHZ	
#define GAS_AO  		B, 1, 	HIGH, MODE_INPUT_ANALOG, 			SPEED_50MHZ	
#define ZE_Rx  			B, 3, 	HIGH, MODE_OUTPUT_PUSH_PULL, 	SPEED_50MHZ	
#define ZE_Tx  			B, 4, 	HIGH, MODE_OUTPUT_PUSH_PULL, 	SPEED_50MHZ	
#define GSM_ON_OFF  B, 5, 	HIGH, MODE_OUTPUT_PUSH_PULL, 	SPEED_50MHZ	
#define SCL_PIN			B, 6, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ	
#define SDA_PIN			B, 7, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ	
#define DHT_DATA  	B, 8, 	HIGH, MODE_INPUT_PULL_UP, 		SPEED_50MHZ	
#define RADIO_SET  	B, 9, 	HIGH, MODE_OUTPUT_PUSH_PULL, 	SPEED_50MHZ
#define GSM_Rx  		B, 10, 	HIGH, MODE_AF_PUSH_PULL, 			SPEED_50MHZ
#define GSM_Tx  		B, 11, 	HIGH, MODE_INPUT_FLOATING, 		SPEED_50MHZ
#define POW_5v0_EN  B, 12, 	HIGH, MODE_OUTPUT_PUSH_PULL, 	SPEED_50MHZ	
#define POW_1v5_EN  B, 13, 	HIGH, MODE_OUTPUT_PUSH_PULL, 	SPEED_50MHZ	
#define PMS_Set  		B, 14, 	HIGH, MODE_OUTPUT_PUSH_PULL, 	SPEED_50MHZ	


#endif //_PINMAP_H_